(princ "\rLoading MED3DTrayFunctions...")
;(setq MED_TRAY_MATERIALWIDTH 0.125) ; Aluminum Tray
;(setq MED_TRAY_MATERIALWIDTH 0.25) ; Fiberglass Tray
;(setq MED_TRAY_TYPEOVERRIDE (list 0.0 1.5 1.5));Use this to set tray forced to Fiberglass Tray Shifts base up and uses C Frames on both sides
(setq MED_TRAY_RUNGSPACING 9.0) ; Planning to use this for Adding Rungs

(defun MEDDraw3DTray (TrayDataList UCSData / TrayPoint1 TrayPoint2 TrayWidth TrayDepth TrayFlange) ; List includes StartPoint EndPoint Width Depth Flange
	(setq TrayPoint1 (nth 0 TrayDataList)
		  TrayPoint2 (nth 1 TrayDataList)
		  TrayWidth  (nth 2 TrayDataList)
		  TrayDepth  (nth 3 TrayDataList)
		  TrayFlange (if MED_TRAYTYPEOVERRIDE (nth 0 MED_TRAYTYPEOVERRIDE) (nth 4 TrayDataList))
		  ;TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBaseEnt (MEDBuild3DTrayBase TrayDataList UCSData) 
		  TrayFlangeEnt1 (MEDBuild3DTrayFlange TrayDataList 1.0 UCSData)
		  TrayFlangeEnt2 (MEDBuild3DTrayFlange TrayDataList -1.0 UCSData)
    )
    (command "union" TrayBaseEnt TrayFlangeEnt1 TrayFlangeEnt2 "")
)
(defun c:traytest()
	(MEDConvertTrayto3d (car (entsel)))
)
(defun MEDConvertTrayTo3D(TrayEntity / TrayPoint1 TrayPoint2)
	(setq TrayEntityData (entget TrayEntity)
		  TrayEntityUCSData (dxf 210 TrayentityData)
	)
	(if (equal (dxf 210 TrayEntityData) (list 0.0 0.0 1.0))
		(command "UCS" "")
		(command "ucs" "OB" trayentity)
	)
	(setq TrayPointlist (bld_lw_ptlist TrayEntity)
		  TrayPointList (car TrayPointlist)
		  TrayEntityPoint1 (append (cdr (nth 0 TrayPointlist)) (list (cdr (assoc 38 TrayEntityData))))
		  TrayEntityPoint1 (trans TrayEntityPoint1 TrayEntityUCSData 1) 
		  TrayEntityPoint2 (append (cdr (nth 1 Traypointlist)) (list (cdr (assoc 38 TrayEntityData))))
		  TrayEntityPoint2 (trans TrayEntityPoint2 TrayEntityUCSData 1)
		  TrayMEDData (xdataget TrayEntity _TRAY)
		  TrayUCSData (dxf 210 TrayEntityData)
	)


	(MEDDraw3DTray (list  TrayEntityPoint1
						  TrayEntityPoint2
			             (nth 2 TrayMEDData) ; Width
			             (nth 5 TrayMEDData) ; Depth
			             (nth 7 TrayMEDData) ; FlangeSize
			       )
					TrayUCSData
	)
)
		  
(defun MEDBuild3DTrayBase (MB3DTB_TrayData TrayUCSData / TrayPoint1 TrayPoint2 TrayAngle)
	(setq TrayPoint1 (nth 0 MB3DTB_TrayData)
		  TrayPoint2 (nth 1 MB3DTB_TrayData)
		  CheckAngle (angle TrayPoint1 TrayPoint2)
		  ExtrudeDir 1
	)
	;(if (not (equal UCSData (list 0.0 0.0 1.0)))
	;	(setq TrayPoint1 (trans TrayPoint1 TrayUCSData 1)
	;		  TrayPoint2 (trans TrayPoint2 TrayUCSData 1)
	;		  ExtrudeDir (if (or (<= CheckAngle (* PI 0.5)) (> CheckAngle (* PI 1.5))) -1 1)
	;	)
	;)
	(setq t1 traypoint1 t2 traypoint2)
	(setq TrayWidth  (nth 2 MB3DTB_TrayData)
		  TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBasePoint1 (polar TrayPoint1 (+ TrayAngle (* PI 0.5)) (* TrayWidth 0.5))
		  TrayBasePoint2 (polar TrayPoint1 (+ TrayAngle (* PI -0.5)) (* TrayWidth 0.5))
		  TrayBasePoint3 (polar TrayPoint2 (+ TrayAngle (* PI -0.5)) (* TrayWidth 0.5))
		  TrayBasePoint4 (polar TrayPoint2 (+ TrayAngle (* PI 0.5)) (* TrayWidth 0.5))
    )
    ;(command "UCS" "")
    (command "3DPOLY" TrayBasePoint1 TrayBasePoint2 TrayBasePoint3 TrayBasePoint4 "C")
    (command "Extrude" "l" "" (* MED_TRAY_MATERIALWIDTH ExtrudeDir)) 
    (setq TrayReturnEntity (entlast))
)
(defun MEDBuild3DTrayFlange (MB3DTF_TrayData MB3DTF_FlipValue UCSData / TrayPoint1 TrayPoint2) ;Flip value is 1.0 normal opposite is -1
	(setq TrayPoint1 (nth 0 MB3DTF_TrayData)
		  TrayPoint2 (nth 1 MB3DTF_TrayData)
		  TrayWidth  (nth 2 MB3DTF_TrayData)
		  TrayDepth  (nth 3 MB3DTF_TrayData)
		  TrayFlange (nth 4 MB3DTF_TrayData)
		 ; UCSPoint1 (trans TrayPoint1 UCSData 0)
		 ; UCSPoint2 (trans TrayPoint2 UCSData 0)
		 ; UCSPoint3 (polar UCSPoint1 (+ (angle UCSPoint1 UCSPoint2) (* PI 0.5)) 1.0)
	)
	;(if (equal (dxf 210 TrayEntityData) (list 0.0 0.0 1.0))
	;	(command "UCS" "")
	;	(progn
	;		(command "UCS" "" "UCS" "n" "3p"  UCSPoint1 UCSPoint2 UCSPoint3)
	;		(setq TrayPoint1 (trans UCSPoint1 0 1)
	;			  TrayPoint2 (trans UCSPoint2 0 1)
	;		)
	;	)
	;)
	(setq TrayLength (distance TrayPoint1 TrayPoint2)
		  TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBasePoint1 (polar TrayPoint1 (+ TrayAngle (* MB3DTF_FlipValue PI 0.5)) (* TrayWidth 0.5))
	)
	(if (< TrayFlange (* 2.0 MED_TRAY_MATERIALWIDTH))
		(progn
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) MED_TRAY_MATERIALWIDTH)
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) MED_TRAY_MATERIALWIDTH)
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 "C")
		)
		(progn
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) (* TrayFlange 0.5))
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ MED_TRAY_MATERIALWIDTH (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (- (* TrayFlange 0.5) MED_TRAY_MATERIALWIDTH))
				  TrayFlangePoint4 (list (nth 0 TrayFlangePoint3) (nth 1 TrayFlangePoint3) (+ (- TrayDepth (* 2.0 MED_TRAY_MATERIALWIDTH)) (nth 2 TrayFlangePoint3)))
				  TrayFlangePoint5 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ (- TrayDepth MED_TRAY_MATERIALWIDTH) (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint6 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint7 (polar TrayFlangePoint6 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (* TrayFlange 0.5))
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 TrayFlangePoint4 TrayFlangePoint5 TrayFlangePoint6 TrayFlangePoint7 "C")
		)
     )
     (command "Extrude" "l" "" "Dir" TrayBasePoint1 (polar TrayBasePoint1 Trayangle TrayLength))
     (setq TrayReturnEntity (entlast))
)

;;Work on Reverse Flange
(defun MEDBuild3DTrayFlange (MB3DTF_TrayData MB3DTF_FlipValue UCSData / TrayPoint1 TrayPoint2) ;Flip value is 1.0 normal opposite is -1
	;(princ "\nHere")
	(setq TrayPoint1 (nth 0 MB3DTF_TrayData)
		  TrayPoint2 (nth 1 MB3DTF_TrayData)
		  TrayWidth  (nth 2 MB3DTF_TrayData)
		  TrayDepth  (nth 3 MB3DTF_TrayData)
		  TrayFlange (nth 4 MB3DTF_TrayData)
		 ; UCSPoint1 (trans TrayPoint1 UCSData 0)
		 ; UCSPoint2 (trans TrayPoint2 UCSData 0)
		 ; UCSPoint3 (polar UCSPoint1 (+ (angle UCSPoint1 UCSPoint2) (* PI 0.5)) 1.0)
	)
	;(if (equal (dxf 210 TrayEntityData) (list 0.0 0.0 1.0))
	;	(command "UCS" "")
	;	(progn
	;		(command "UCS" "" "UCS" "n" "3p"  UCSPoint1 UCSPoint2 UCSPoint3)
	;		(setq TrayPoint1 (trans UCSPoint1 0 1)
	;			  TrayPoint2 (trans UCSPoint2 0 1)
	;		)
	;	)
	;)
	(setq TrayLength (distance TrayPoint1 TrayPoint2)
		  TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBasePoint1 (polar TrayPoint1 (+ TrayAngle (* MB3DTF_FlipValue PI 0.5)) (* TrayWidth 0.5))
	)
	(if (< (abs TrayFlange) (* 2.0 MED_TRAY_MATERIALWIDTH))
		(progn
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) MED_TRAY_MATERIALWIDTH)
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) MED_TRAY_MATERIALWIDTH)
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 "C")
		)
		(progn
			(if (< TrayFlange 0.0)
				(setq FlangeFLIP T)
				(setq FlangeFLIP nil)
			)
				
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) (* TrayFlange 0.5))
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ MED_TRAY_MATERIALWIDTH (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (- (* TrayFlange 0.5) (if FlangeFlip (* -1 MED_TRAY_MATERIALWIDTH) MED_TRAY_MATERIALWIDTH)))
				  TrayFlangePoint4 (list (nth 0 TrayFlangePoint3) (nth 1 TrayFlangePoint3) (+ (- TrayDepth (* 2.0 MED_TRAY_MATERIALWIDTH)) (nth 2 TrayFlangePoint3)))
				  TrayFlangePoint5 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ (- TrayDepth MED_TRAY_MATERIALWIDTH) (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint6 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint7 (polar TrayFlangePoint6 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (* TrayFlange 0.5))
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 TrayFlangePoint4 TrayFlangePoint5 TrayFlangePoint6 TrayFlangePoint7 "C")
		)
     )
     (command "Extrude" "l" "" "Dir" TrayBasePoint1 (polar TrayBasePoint1 Trayangle TrayLength))
     (setq TrayReturnEntity (entlast))
)


;This function simply needs same info as tray, but then pass it the offset entity form the MED Centerline Copy and it will create it nice and smooth
(defun MEDBuild3DTrayFitFlange (MB3DTF_TrayData MB3DTF_FlipValue MB3DTF_Entity NotVerticalTrayFlag / TrayPoint1 TrayPoint2 TrayAngle) ;Flip value is 1.0 normal opposite is -1
	(setq TrayPoint1 (nth 0 MB3DTF_TrayData)
		  TrayPoint2 (nth 1 MB3DTF_TrayData)
		  TrayWidth  (nth 2 MB3DTF_TrayData)
		  TrayDepth  (nth 3 MB3DTF_TrayData)
		  TrayFlange (nth 4 MB3DTF_TrayData)
		  TrayLength (distance TrayPoint1 TrayPoint2)
		  TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBasePoint1 (polar TrayPoint1 (+ TrayAngle (* MB3DTF_FlipValue PI 0.5)) (* TrayWidth 0.5))
	)
	(if (< TrayFlange (* 2.0 MED_TRAY_MATERIALWIDTH))
		(progn
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) MED_TRAY_MATERIALWIDTH)
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) MED_TRAY_MATERIALWIDTH)
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 "C")
			(setq ExtrudeEntity (entlast))
		)
		(progn
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) (* TrayFlange 0.5))
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ MED_TRAY_MATERIALWIDTH (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (- (* TrayFlange 0.5) MED_TRAY_MATERIALWIDTH))
				  TrayFlangePoint4 (list (nth 0 TrayFlangePoint3) (nth 1 TrayFlangePoint3) (+ (- TrayDepth (* 2.0 MED_TRAY_MATERIALWIDTH)) (nth 2 TrayFlangePoint3)))
				  TrayFlangePoint5 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ (- TrayDepth MED_TRAY_MATERIALWIDTH) (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint6 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint7 (polar TrayFlangePoint6 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (* TrayFlange 0.5))
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 TrayFlangePoint4 TrayFlangePoint5 TrayFlangePoint6 TrayFlangePoint7 "C")
			(setq ExtrudeEntity (entlast))
		)
			
     )
    (setq t1 VerticalTrayFlag)
     (if NotVerticalTrayFlag
     	 (command "offset" (distance TrayPoint1 TrayBasePoint1) MB3DTF_Entity TrayBasePoint1 "")
     	 (command "Copy" MB3DTF_Entity "" TrayPoint1 TrayBasePoint1)
     )
     (setq PathEntity (entlast))
     (command "Extrude" ExtrudeEntity "" "Path" Pathentity)
     (setq TrayReturnEntity (entlast))
)


;;Work on negative flange
(defun MEDBuild3DTrayFitFlange (MB3DTF_TrayData MB3DTF_FlipValue MB3DTF_Entity NotVerticalTrayFlag / TrayPoint1 TrayPoint2 TrayAngle) ;Flip value is 1.0 normal opposite is -1
	(setq TrayPoint1 (nth 0 MB3DTF_TrayData)
		  TrayPoint2 (nth 1 MB3DTF_TrayData)
		  TrayWidth  (nth 2 MB3DTF_TrayData)
		  TrayDepth  (nth 3 MB3DTF_TrayData)
		  TrayFlange (nth 4 MB3DTF_TrayData)
		  TrayLength (distance TrayPoint1 TrayPoint2)
		  TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBasePoint1 (polar TrayPoint1 (+ TrayAngle (* MB3DTF_FlipValue PI 0.5)) (* TrayWidth 0.5))
	)
	(if (< (abs TrayFlange) (* 2.0 MED_TRAY_MATERIALWIDTH))
		(progn
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) MED_TRAY_MATERIALWIDTH)
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) MED_TRAY_MATERIALWIDTH)
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 "C")
			(setq ExtrudeEntity (entlast))
		)
		(progn
			(if (< TrayFlange 0.0)
				(setq FlangeFLIP T)
				(setq FlangeFLIP nil)
			)
			
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) (* TrayFlange 0.5))
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ MED_TRAY_MATERIALWIDTH (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (- (* TrayFlange 0.5) (if FlangeFlip (* -1 MED_TRAY_MATERIALWIDTH) MED_TRAY_MATERIALWIDTH)))
				  TrayFlangePoint4 (list (nth 0 TrayFlangePoint3) (nth 1 TrayFlangePoint3) (+ (- TrayDepth (* 2.0 MED_TRAY_MATERIALWIDTH)) (nth 2 TrayFlangePoint3)))
				  TrayFlangePoint5 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ (- TrayDepth MED_TRAY_MATERIALWIDTH) (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint6 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint7 (polar TrayFlangePoint6 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (* TrayFlange 0.5))
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 TrayFlangePoint4 TrayFlangePoint5 TrayFlangePoint6 TrayFlangePoint7 "C")
			(setq ExtrudeEntity (entlast))
		)
			
     )
    (setq t1 VerticalTrayFlag)
     (if NotVerticalTrayFlag
     	 (command "offset" (distance TrayPoint1 TrayBasePoint1) MB3DTF_Entity TrayBasePoint1 "")
     	 (command "Copy" MB3DTF_Entity "" TrayPoint1 TrayBasePoint1)
     )
     (setq PathEntity (entlast))
     (command "Extrude" ExtrudeEntity "" "Path" Pathentity)
     (setq TrayReturnEntity (entlast))
)



;I used this to create a 90 degree Elbow travling up or at least the one line of it.
;(maketray (list (list (list 0.0 0.0) nil) (list (list 5.0 0.0) (* (* PI 0.5) 0.25)) (list (list 17.0 12.0) nil) (list (list 17.0 17.0) nil)) nil nil)

;Thsi one works to creat a 90 degree elbow down
;(maketray (list (list (list 0.0 0.0) nil) (list (list 5.0 0.0) (* -1.0 (* PI 0.5) 0.25)) (list (list 17.0 -12.0) nil) (list (list 17.0 -17.0) nil)) nil nil)
(defun c:QVTest()
	(setq _ZFLAG T)
	(setq t-pt1 (list 0.0 0.0)
		  t-pt2 (list 5.0 0.0)
		  t-pt3 (list 17.0 -12.0)
		  t-pt4 (list 17.0 -17.0)
		  t-list (list (list t-pt1 nil)
					   (list t-pt2 (* -1.0 (med_tan (* (* PI 0.5) 0.25))))
					   (list t-pt3 nil)
					   (list t-pt4 nil)
				 )
	)
	(maketray t-list nil nil)
)

(defun c:trayfittest()
	(MEDConvertTrayElbowto3d (car (entsel)))
)
(defun MEDConvertTrayElbowTo3D(TrayEntity)
	(setq TrayEntityData (entget TrayEntity)
		  TrayMEDData (xdataget TrayEntity _FITTING)
	)
	(if (equal (dxf 210 TrayEntityData) (list 0.0 0.0 1.0))
		(command "UCS" "")
		(command "ucs" "OB" trayentity)
	)
	(MEDDraw3DTrayFit (list nil
			             	nil
			             (nth 2 TrayMEDData) ; Width
			             (nth 5 TrayMEDData) ; Depth
			             (nth 6 TrayMEDData) ; FlangeSize
			       )
		           TrayEntity
	)
)

(defun MEDDraw3DTrayFit (TrayDataList TrayCenterLine / TrayPoint1 TrayPoint2 TrayWidth TrayDepth TrayFlange) ; List includes StartPoint EndPoint Width Depth Flange
	(setq t1e Traycenterline)
	(setq t1d traydatalist)
	(setq Traypoints (bld_lw_ptlist TrayCenterLine)
		  TrayCenterLineData (entget TrayCenterLine)
		  TrayPoint38 (dxf 38 TrayCenterLineData)
	)
	(setq TrayPoint1 (trans (append (cdr (nth 0 (car TrayPoints))) (list traypoint38)) T1e 1) 
		  TrayPoint2 (trans (append (cdr (nth 1 (car TrayPoints))) (list traypoint38)) T1e 1)
	)
	(if (setq TrayfitVData (vtrayxdataget TrayCenterline))
		(progn
			;(sd)
			(command "UCS" "New" "3P" TrayPoint1 TrayPoint2 (list (car TrayPoint1) (cadr Traypoint1) (- (caddr TrayPoint1) 10.0)));(* 1.0 (nth 3 trayfitvdata)))))
			;(sd)
			(setq TrayPoint1 (trans (append (cdr (nth 0 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1) 
		          TrayPoint2 (trans (append (cdr (nth 1 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		    )
		 )
	)
	(setq TrayWidth  (nth 2 TrayDataList)
		  TrayDepth  (nth 3 TrayDataList)
		  TrayFlange (nth 4 TrayDataList)
		  TrayDataList (list TrayPoint1 TrayPoint2 TrayWidth TrayDepth TrayFlange)
		  ;TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBaseEnt (MEDBuild3DTrayFitBase TrayDataList TrayCenterLine) 
		  TrayFlangeEnt1 (MEDBuild3DTrayFitFlange TrayDataList 1.0 TrayCenterLine (not (vtrayxdataget TrayCenterline)))
		  TrayFlangeEnt2 (MEDBuild3DTrayFitFlange TrayDataList -1.0 TrayCenterLine (not (vtrayxdataget TrayCenterline)))
		  ;TrayFlangeEnt1 (MEDBuild3DTrayFitFlange TrayDataList 1.0 TrayCenterLine (equal (dxf 210 TrayCenterLineData) (list 0.0 0.0 1.0)))
		  ;TrayFlangeEnt2 (MEDBuild3DTrayFitFlange TrayDataList -1.0 TrayCenterLine (equal (dxf 210 TrayCenterLineData) (list 0.0 0.0 1.0)))
    )
    (command "union" TrayBaseEnt TrayFlangeEnt1 TrayFlangeEnt2 "")
)    	  
(defun MEDBuild3DTrayFitBase (MB3DTB_TrayData MB3DTF_Entity / TrayPoint1 TrayPoint2 TrayAngle)
	(setq t1 MB3DTB_TrayData)
	(setq TrayPoint1 (nth 0 MB3DTB_TrayData)
		  TrayPoint2 (nth 1 MB3DTB_TrayData)
		  TrayWidth  (nth 2 MB3DTB_TrayData)
		  TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBasePoint1 (polar TrayPoint1 (+ TrayAngle (* PI 0.5)) (* TrayWidth 0.5))
		  TrayBasePoint2 (polar TrayPoint1 (+ TrayAngle (* PI -0.5)) (* TrayWidth 0.5))
		  TrayBasePoint3 (list (car TrayBasePoint2) (cadr TrayBasepoint2) (+ (caddr TrayBasePoint2) MED_TRAY_MATERIALWIDTH))
		  TrayBasePoint4 (list (car TrayBasePoint1) (cadr TrayBasepoint1) (+ (caddr TrayBasePoint1) MED_TRAY_MATERIALWIDTH))
     )
     (command "Copy" MB3DTF_Entity "" "0,0,0" "0,0,0")
     (setq PathEntity (entlast))
     (command "3DPOLY" TrayBasePoint1 TrayBasePoint2 TrayBasePoint3 TrayBasePoint4 "C")
     (command "Extrude" "l" "" "path" Pathentity)
     (setq TrayReturnEntity (entlast))
)

(defun MEDSet3DTrayLayer(trayentity)
	(setq trayentityLayer (dxf 8 (entget trayentity))
		  traydesc (substr trayentityLayer 10)
		  trayLayer (strcat "MEDTRAY" traydesc)
		  3dtraylayername (strcat "MED_3DTRAY-" traydesc)
	)
	(if (not (tblsearch "layer" 3DTrayLayerName))
		(progn
			(setq NewLayColor (MEDGetLayerColor TrayLayer)
		          NewLayData (list 3dTrayLayerName NewLayColor "Continuous" nil)
		    )
		    (medsmlayer newlaydata)
		)
		(setvar "CLAYER" 3DtrayLayerName)
	)
)
	
	

(defun c:Make3DTray()
	(smlayer _MED3DTRAY)
	(command "vpoint" "1,1,1")
	(initget "3DS Dwg Layer")
	(setq outputformat (getkword "\n Output to 3DS Layer <Dwg>: "))
	(if (not outputformat)
	  (setq outputformat "Dwg")
	)
	(setq 3douttray (ssget "x" (list (list -3 (list "MED_TRAY")))))
	(if 3douttray
	  (progn
	    (setq trayoutnum (sslength 3douttray)
	   trayoutcnt 0
	    )
	    (while (< trayoutcnt trayoutnum)
	    	  (setq trayent (ssname 3douttray trayoutcnt))
	    	  (MEDSet3DTrayLayer trayent)
	    	  (MEDConvertTrayto3d trayent)
	    	  (setq trayoutcnt (1+ trayoutcnt))
	    )
	  )
	)
	(setq 3douttray (ssget "x" (list (list -3 (list "MED_FITTING")))))
	(if 3douttray
	   (progn
	     (setq trayoutnum (sslength 3douttray)
	     	   trayoutcnt 0
	     )
	     (while (< trayoutcnt trayoutnum)
	     	 (setq trayent (ssname 3douttray trayoutcnt))
	     	 (MEDSet3DTrayLayer trayent)
	     	 (MEDConvertTrayFittingsTo3D trayent)
	     	 (setq trayoutcnt (1+ trayoutcnt))
	     )
	   )
	 )
	(command "UCS" "")
	(cond
    ((= outputformat "3DS")
      (Prompt "\nMake3dtray will export to 3ds file:")
      (if (not c:3dsout)
	(arxload "render")
      )
      (setq 3dsoutfname (getfiled "Select file name for 3Dtray output" (substr (getvar "dwgname") 1 (- (strlen (getvar "dwgname")) 4)) "3ds" 1))
      (c:3dsout (ssget "X" (list (cons 0 "3dsolid") (cons 8 (nth 0 _MED3DTRAY)))) 0 0 30 0.1 3dsoutfname)
      (command "erase" (ssget "X" (list (cons 0 "3dsolid") (cons 8 (nth 0 _MED3DTRAY)))) "")
      (command "plan" "")
    )
    ;;testing default path as the drawing prefix
    ;(setq 3dsoutfname (getfiled "Select file name for 3Dtray output" (substr (getvar "dwgname") 1 (- (strlen (getvar "dwgname")) 4)) "dwg" 1))
    ((= outputformat "Dwg")
      (setq 3dsoutfname (getfiled "Select file name for 3Dtray output" (getvar "dwgprefix") "dwg" 1))
      (if (findfile 3dsoutfname)
	(command "wblock" 3dsoutfname "y" "")
	(command "wblock" 3dsoutfname "")
      )
      ;(command (list 0.0 0.0 0.0) (ssget "X" (list (cons 0 "3dsolid") (cons 8 (nth 0 _MED3DTRAY)))) "")
      (command (list 0.0 0.0 0.0) (ssget "X" (list (cons 0 "3dsolid") )) "")
      (command "plan" "")
    )
    ((= outputformat "Layer")
      ;(command "-layer" "off" "*" "" "On" (nth 0 _MED3DTRAY) "")
      (prompt "\nUse the PLAN command to return to plan view:")
    )
  )

)

(defun MEDConvertTrayFittingsTo3D (trayfitent)
  (setq fitptbllist (bld_lw_ptlist trayfitent)
  	    fitptlist   (nth 0 fitptbllist)
  	    fitbllist   (nth 1 fitptbllist)
  	    Trayfitdata (xdataget trayfitent _FITTING)
  	    fitwidth    (nth 2 trayfitdata)
  	    fitdpth     (nth 5 trayfitdata)
  	    fitalt      (nth 4 trayfitdata)
  	    m3delev     (getvar "ELEVATION")
  	    trayfitentdata (entget trayfitent)
  )
  (setvar "ELEVATION" (dxf 38 trayfitentdata))
  
  (cond
    ((= (length fitptlist) 4)
    		(MEDConvertTrayElbowTo3D trayfitent)
    )
    ((= (length fitptlist) 7)
    		(MEDConvertTrayTeeTo3D trayfitent)
    )
    ((= (length fitptlist) 10)
    	  	(MEDConvertTrayTeeTo3D trayfitent)
    )
    ((and (= (length fitptlist) 2)
	  (= 18.0 (distance (cdr (nth 0 fitptlist)) (cdr (nth 1 fitptlist)))))
       (MEDConvertTrayReducerTo3d trayfitent)
    )
    ((and (= (length fitptlist) 2)
          (> (rem (distance (cdr (nth 0 fitptlist)) (cdr (nth 1 fitptlist))) 1.0) 0.0))
       (MEDConvertTrayLRReducerTo3d trayfitent)
     )
    (T nil)
    
  )
  (setvar "ELEVATION" m3delev)
  
)

(defun MEDCopyEntity(EntityToCopy / CopyEntityData)
	(setq CopyEntityData (entget EntityToCopy)
		  CopyEntityData (cdr CopyEntityData)
	      CopyEntityData (entmake CopyEntityData)
	)
	(if CopyentityData
		(setq ReturnEntity (entlast))
		(setq ReturnEntity nil)
	)
	ReturnEntity
)


(defun MEDDraw3DTrayTeeCrossFit (TrayDataList TrayCenterLine /
		  TrayPoint1 TrayPoint2 TrayPoint3 TrayPoint4 TrayPoint5 TrayPoint6 TrayPoint7 TrayWidth TrayDepth TrayFlange) ; List includes StartPoint EndPoint Width Depth Flange
	(setq Traypoints (bld_lw_ptlist TrayCenterLine)
		  TrayCenterLineData (entget TrayCenterLine)
		  TrayPoint38 (dxf 38 TrayCenterLineData)
		  TrayPoint1 (trans (append (cdr (nth 0 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1) 
		  TrayPoint2 (trans (append (cdr (nth 1 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  TrayPoint3 (trans (append (cdr (nth 2 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  TrayPoint4 (trans (append (cdr (nth 3 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  TrayPoint5 (trans (append (cdr (nth 4 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  TrayPoint6 (trans (append (cdr (nth 5 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  TrayPoint7 (trans (append (cdr (nth 6 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  TrayWidth  (nth 2 TrayDataList)
		  TrayDepth  (nth 3 TrayDataList)
		  TrayFlange (nth 4 TrayDataList)
		  TrayDataList (list TrayPoint1 TrayPoint2 TrayWidth TrayDepth TrayFlange)
		  ;TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBaseEnt (MEDBuild3DTrayBaseFromOutline TrayCenterLine)
		  TrayElevation (setvar "ELEVATION" TrayPoint38)
		  TempTrayCenter (MEDmaketray (list (list TrayPoint1 nil) (list TrayPoint2 (cdr (nth 1 (cadr Traypoints)))) (list TrayPoint3 nil) (list TrayPoint4 nil)) nil nil (MEDGetCurrentOCS))
		  TempTrayCenter (entlast)
		  TrayFlangeEnt1 (MEDBuild3DTrayFitFlange TrayDataList 1.0 TempTrayCenter (not (vtrayxdataget TrayCenterline)))
		  TempTrayCenter (entdel TempTrayCenter)
		  TrayDataList (list TrayPoint4 TrayPoint5 TrayWidth TrayDepth TrayFlange)
		  TrayElevation (setvar "ELEVATION" TrayPoint38)
		  TempTrayCenter (MEDmaketray (list (list TrayPoint4 nil) (list TrayPoint5 (cdr (nth 4 (cadr Traypoints)))) (list TrayPoint6 nil) (list TrayPoint7 nil)) nil nil (MEDGetCurrentOCS))
		  TempTrayCenter (entlast)
		  TrayFlangeEnt2 (MEDBuild3DTrayFitFlange TrayDataList 1.0 TempTrayCenter (not (vtrayxdataget TrayCenterline)))
		  TempTrayCenter (entdel TempTrayCenter)
    )
    (if (= (length (car TrayPoints)) 7)
    	(progn
    		(setq TrayDataList (list TrayPoint7 TrayPoint1 TrayWidth TrayDepth TrayFlange)
    			  TrayFlangeEnt3 (MEDBuild3DTrayFlange TrayDataList 1.0 (dxf 210 TRayCenterLineData))
    		)
    		(command "union" TrayBaseEnt TrayFlangeEnt1 TrayFlangeEnt2 TrayFlangeEnt3 "")
    	)
    	(progn
    		(setq TrayPoint8 (trans (append (cdr (nth 7 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
    			  TrayPoint9 (trans (append (cdr (nth 8 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
    			  TrayPoint10 (trans (append (cdr (nth 9 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
    			  TrayDataList (list TrayPoint7 TrayPoint8 TrayWidth TrayDepth TrayFlange)
    			  TrayElevation (setvar "ELEVATION" TrayPoint38)
    			  TempTrayCenter (maketray (list (list TrayPoint7 nil) (list TrayPoint8 (cdr (nth 4 (cadr Traypoints)))) (list TrayPoint9 nil) (list TrayPoint10 nil)) nil nil)
    			  TempTrayCenter (entlast)
    			  TrayFlangeEnt3 (MEDBuild3DTrayFitFlange TrayDataList 1.0 TempTrayCenter (not (vtrayxdataget TrayCenterline)))
    			  TempTrayCenter (entdel TempTrayCenter)
    			  TrayDataList (list TrayPoint10 TrayPoint9 TrayWidth TrayDepth TrayFlange)
    			  TrayElevation (setvar "ELEVATION" TrayPoint38)
    			  TempTrayCenter (maketray (list (list TrayPoint10 nil) (list TrayPoint9 (cdr (nth 1 (cadr Traypoints)))) (list TrayPoint2 nil) (list TrayPoint1 nil)) nil nil)
    			  TempTrayCenter (entlast)
    			  TrayFlangeEnt4 (MEDBuild3DTrayFitFlange TrayDataList 1.0 TempTrayCenter (not (vtrayxdataget TrayCenterline)))
    			  TempTrayCenter (entdel TempTrayCenter)
    		)
    		(command "union" TrayBaseEnt TrayFlangeEnt1 TrayFlangeEnt2 TrayFlangeEnt3 TrayFlangeEnt4 "")
    	)
    		
    )
)    	 
    
(defun MEDBuild3DTrayBaseFromOutline (TrayCenterline)
	(setq TrayFittingData (xdataget TrayCenterLine _FITTING))
	(mtrayfit TrayCenterLine TrayFittingData T)
	(setq TrayFittingOutlineEnt (entlast))
	(command "Extrude" "l" "" MED_TRAY_MATERIALWIDTH)
    (setq TrayReturnEntity (entlast))
)

(defun c:trayteetest()
	(MEDConvertTrayTeeTo3d (car (entsel)))
)
(defun MEDConvertTrayTeeTo3D(TrayEntity)
	(setq TrayEntityData (entget TrayEntity)
		  TrayMEDData (xdataget TrayEntity _FITTING)
	)
	(if (equal (dxf 210 TrayEntityData) (list 0.0 0.0 1.0))
		(command "UCS" "")
		(command "ucs" "OB" trayentity)
	)
	(MEDDraw3DTrayTeeCrossFit (list nil
			             nil
			             (nth 2 TrayMEDData) ; Width
			             (nth 5 TrayMEDData) ; Depth
			             (nth 6 TrayMEDData) ; FlangeSize
			       )
		           TrayEntity
	)
)

(defun MEDBuild3DTrayFlangeFromEntity (MB3DTF_TrayData MB3DTF_FlipValue MB3DTF_Entity / TrayPoint1 TrayPoint2 TrayAngle) ;Flip value is 1.0 normal opposite is -1
	(setq TrayPoint1 (nth 0 MB3DTF_TrayData)
		  TrayPoint2 (nth 1 MB3DTF_TrayData)
		  TrayWidth  (nth 2 MB3DTF_TrayData)
		  TrayDepth  (nth 3 MB3DTF_TrayData)
		  TrayFlange (nth 4 MB3DTF_TrayData)
		  TrayLength (distance TrayPoint1 TrayPoint2)
		  TrayAngle  (angle TrayPoint1 TrayPoint2)
		  TrayBasePoint1 (polar TrayPoint1 (+ TrayAngle (* MB3DTF_FlipValue PI 0.5)) (* TrayWidth 0.5))
;		  TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) (* TrayFlange 0.5))
;		  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ MED_TRAY_MATERIALWIDTH (nth 2 TrayFlangePoint1)))
;		  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (- (* TrayFlange 0.5) MED_TRAY_MATERIALWIDTH))
;		  TrayFlangePoint4 (list (nth 0 TrayFlangePoint3) (nth 1 TrayFlangePoint3) (+ (- TrayDepth (* 2.0 MED_TRAY_MATERIALWIDTH)) (nth 2 TrayFlangePoint3)))
;		  TrayFlangePoint5 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ (- TrayDepth MED_TRAY_MATERIALWIDTH) (nth 2 TrayFlangePoint1)))
;		  TrayFlangePoint6 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
;		  TrayFlangePoint7 (polar TrayFlangePoint6 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (* TrayFlange 0.5))
;     )
;     (command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 TrayFlangePoint4 TrayFlangePoint5 TrayFlangePoint6 TrayFlangePoint7 "C")
;     (command "Extrude" "l" "" "Path" MB3DTF_Entity)
;     (setq TrayReturnEntity (entlast))
	)
	(if (< (abs TrayFlange) (* 2.0 MED_TRAY_MATERIALWIDTH))
		(progn
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) MED_TRAY_MATERIALWIDTH)
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) MED_TRAY_MATERIALWIDTH)
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 "C")
		)
		(progn
			(if (< TrayFlange 0.0)
				(setq FlangeFLIP T)
				(setq FlangeFLIP nil)
			)
			(setq t1 MB3Dtf_TrayData t2 Traybasepoint1 t3 Traybasepoint2)
			(setq TrayFlangePoint1 (polar TrayBasePoint1 (+ TrayAngle (*  MB3DTF_FlipValue PI 0.5)) (* TrayFlange 0.5))
				  TrayFlangePoint2 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ MED_TRAY_MATERIALWIDTH (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint3 (polar TrayFlangePoint2 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (- (* TrayFlange 0.5) (if FlangeFlip (* -1 MED_TRAY_MATERIALWIDTH) MED_TRAY_MATERIALWIDTH)))
				  TrayFlangePoint4 (list (nth 0 TrayFlangePoint3) (nth 1 TrayFlangePoint3) (+ (- TrayDepth (* 2.0 MED_TRAY_MATERIALWIDTH)) (nth 2 TrayFlangePoint3)))
				  TrayFlangePoint5 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ (- TrayDepth MED_TRAY_MATERIALWIDTH) (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint6 (list (nth 0 TrayFlangePoint1) (nth 1 TrayFlangePoint1) (+ TrayDepth (nth 2 TrayFlangePoint1)))
				  TrayFlangePoint7 (polar TrayFlangePoint6 (+ TrayAngle (* PI  MB3DTF_FlipValue -0.5)) (* TrayFlange 0.5))
			)
			(command "3DPOLY" TrayBasePoint1 TrayFlangePoint1 TrayFlangePoint2 TrayFlangePoint3 TrayFlangePoint4 TrayFlangePoint5 TrayFlangePoint6 TrayFlangePoint7 "C")
		)
     )
     ;(command "Extrude" "l" "" "Dir" TrayBasePoint1 (polar TrayBasePoint1 Trayangle TrayLength))
     (command "Extrude" "l" "" "Path" MB3DTF_Entity)
     (setq TrayReturnEntity (entlast))
)

(defun MEDDraw3DTrayStraightReducer (TrayDataList TrayCenterLine /
		  TrayPoint1 TrayPoint2 TrayPoint3 TrayPoint4 TrayWidth TrayDepth TrayFlange TrayAngle) ; List includes StartPoint EndPoint Width Depth Flange
	(setq Traypoints (bld_lw_ptlist TrayCenterLine)
		  TrayReducerData (entget TrayCenterLine)
		  TrayPoint38 (dxf 38 TrayReducerData)
		  TrayPoint1 (trans (append (cdr (nth 0 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  t1 TrayPoint1
		  TrayPoint2 (trans (append (cdr (nth 1 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  t2 TrayPoint2
		  t3 Trayreducerdata
		  TrayWidth  (nth 2 TrayDataList)
		  TrayDepth  (nth 3 TrayDataList)
		  TrayFlange (nth 4 TrayDataList)
		  TrayAltWidth (nth 4 (xdataget TrayCenterLine _FITTING))
		  TrayAngle  (angle TrayPoint1 TrayPoint2)
		  tandist 7.0
	      apt1 (polar TrayPoint1 (- TrayAngle (* PI 0.5)) (* 0.5 (* _PLOTSCALE TrayWidth)))
	      apt2 (polar TrayPoint2 (+ TrayAngle (* PI 0.5)) (* 0.5 (* _PLOTSCALE TrayWidth)))
	      apt3 (polar apt1 TrayAngle (* _PLOTSCALE tandist))
	      apt4 (polar apt2 TrayAngle (* _PLOTSCALE tandist))
	      bpt1 (polar TrayPoint2 (+ TrayAngle (* PI 0.5)) (* 0.5 (* _PLOTSCALE TrayAltWidth)))
	      bpt2 (polar TrayPoint2 (- TrayAngle (* PI 0.5)) (* 0.5 (* _PLOTSCALE TrayAltWidth)))
	      bpt3 (polar bpt1 (+ PI TrayAngle) (* _PLOTSCALE tandist))
	      bpt4 (polar bpt2 (+ PI TrayAngle) (* _PLOTSCALE tandist))
		  TrayDataList (list TrayPoint1 TrayPoint2 TrayWidth TrayDepth TrayFlange)
		  TrayBaseEnt (MEDBuild3DTrayBaseFromOutline TrayCenterLine)
		  mlist (list (list apt2 nil) (list apt4 nil) (list bpt3 nil) (list bpt1 nil))   
		  TempTrayCenter (MEDmaketray mlist nil nil (MEDGetCurrentOCS))
		  TempTrayCenter (entlast)
		  TrayFlangeEnt1 (MEDBuild3DTrayFlangeFromEntity TrayDataList 1.0 TempTrayCenter)
		  mlist (list (list apt1 nil) (list apt3 nil) (list bpt4 nil) (list bpt2 nil))   
		  TempTrayCenter (MEDmaketray mlist nil nil (MEDGetCurrentOCS))
		  TempTrayCenter (entlast)
		  TrayFlangeEnt2 (MEDBuild3DTrayFlangeFromEntity TrayDataList -1.0 TempTrayCenter)
    )
    (command "union" TrayBaseEnt TrayFlangeEnt1 TrayFlangeEnt2 "")
)

(defun MEDDraw3DTrayLeftOrRightReducer (TrayDataList TrayCenterLine /
		  TrayPoint1 TrayPoint2 TrayPoint3 TrayPoint4 TrayWidth TrayDepth TrayFlange TrayAngle) ; List includes StartPoint EndPoint Width Depth Flange
	(setq Traypoints (bld_lw_ptlist TrayCenterLine)
		  TrayReducerData (entget TrayCenterLine)
		  TrayPoint38 (dxf 38 TrayReducerData)
		  TrayPoint1 (trans (append (cdr (nth 0 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  TrayPoint2 (trans (append (cdr (nth 1 (car TrayPoints))) (list traypoint38)) TrayCenterLine 1)
		  t1 TrayPoint1
		  t2 TrayPoint2
		  TrayWidth  (nth 2 TrayDataList)
		  TrayDepth  (nth 3 TrayDataList)
		  TrayFlange (nth 4 TrayDataList)
		  TrayReducerData (xdataget TrayCenterLine _FITTING)
		  TrayAltWidth (nth 4 TrayReducerData)
		  ReducerData (med_getdesc "FITTING" (nth 3 TrayReducerData)) 
	)
	(if (= (strcase (substr ReducerData 1 1)) "L")
		(setq DirectionFactor 1)
		(setq DirectionFactor -1)
	)
	(setq TrueAngle  (angle TrayPoint2 TrayPoint1)
		  tandist 7.0
		  ReducerLength (distance TrayPoint1 TrayPoint2)
		  StockReducerLength 18.0
		  HalfAlt (* (- TrayWidth TrayAltWidth 0.5))
		  HalfSize2 (* TrayAltWidth 0.5)
		  SinOfAngle (/ ReducerLength StockReducerLength)
		  CosOfAngle (/ halfAlt StockReducerLength)
		  AngleOfFittingLine (* DirectionFactor (atan (/ SinOfAngle CosOfAngle)))
		  TrayAngle (+ TrueAngle AngleOfFittingLine)
		  OtherPoint2 (polar TrayPoint2 TrayAngle HalfAlt)
		  Trayangle (angle TrayPoint1 OtherPoint2)
		  OtherPoint2 (polar TrayPoint1 TrayAngle StockReducerLength)
	      apt1 (polar TrayPoint2 (+ TrayAngle (* DirectionFactor (* PI 0.5))) (* _PLOTSCALE HalfSize2))
	      apt2 (polar apt1 (+ TrayAngle PI) (* StockReducerLength _PLOTSCALE)) 
	      apt3 (polar  apt2 (- Trayangle (* DirectionFactor (* PI 0.5))) (* TrayWidth _PLOTSCALE))
	      t37 TrayAngle
	      apt4 (polar apt3 TrayAngle (* tandist _PLOTSCALE))
	      apt6 (polar TrayPoint2 (+ TrayAngle (* DirectionFactor (* PI 1.5))) (* _PLOTSCALE HalfSize2))
	      apt5 (polar apt6 (+ TrayAngle PI) (* tandist _PLOTSCALE))
		  TrayDataList (list TrayPoint1 TrayPoint2 TrayWidth TrayDepth TrayFlange)
		  TrayBaseEnt (MEDBuild3DTrayBaseFromOutline TrayCenterLine)
		  UseThisAngle (angle apt3 apt4)
		  OtherPoint2 (polar TrayPoint1 UseThisAngle StockReducerLength)
		  mlist (list (list apt2 nil) (list apt1 nil))   
		  TempTrayCenter (MEDmaketray mlist nil nil (MEDGetCurrentOCS))
		  TempTrayCenter (entlast)
		  TrayDataList (list TrayPoint1 OtherPoint2 TrayWidth TrayDepth TrayFlange)
		  TrayFlangeEnt1 (MEDBuild3DTrayFlangeFromEntity TrayDataList (* 1.0 DirectionFactor) TempTrayCenter)
		  t5 Trayangle
		  mlist (list (list apt3 nil) (list apt4 nil) (list apt5 nil) (list apt6 nil))   
		  TempTrayCenter (MEDmaketray mlist nil nil (MEDGetCurrentOCS))
		  TempTrayCenter (entlast)
		  TrayFlangeEnt2 (MEDBuild3DTrayFlangeFromEntity TrayDataList (* -1.0 DirectionFactor) TempTrayCenter)
    )
    (command "union" TrayBaseEnt TrayFlangeEnt1 TrayFlangeEnt2 "")
)   


(defun c:trayretest()
	(MEDConvertTrayReducerTo3d (car (entsel)))
)
(defun MEDConvertTrayReducerTo3D(TrayEntity)
	(setq TrayEntityData (entget TrayEntity)
		  TrayMEDData (xdataget TrayEntity _FITTING)
	)
	(if (equal (dxf 210 TrayEntityData) (list 0.0 0.0 1.0))
		(command "UCS" "")
		(command "ucs" "OB" trayentity)
	)
	(MEDDraw3DTrayStraightReducer (list nil
			             nil
			             (nth 2 TrayMEDData) ; Width
			             (nth 5 TrayMEDData) ; Depth
			             (nth 6 TrayMEDData) ; FlangeSize
			       )
		           TrayEntity
	)
)
      	  
	
(defun c:traylrretest()
	(MEDConvertTrayLRReducerTo3d (car (entsel)))
)
(defun MEDConvertTrayLRReducerTo3D(TrayEntity)
	(setq TrayEntityData (entget TrayEntity)
		  TrayMEDData (xdataget TrayEntity _FITTING)
	)
	(if (equal (dxf 210 TrayEntityData) (list 0.0 0.0 1.0))
		(command "UCS" "")
		(command "ucs" "OB" trayentity)
	)
	(MEDDraw3DTrayLeftOrRightReducer (list nil
			             nil
			             (nth 2 TrayMEDData) ; Width
			             (nth 5 TrayMEDData) ; Depth
			             (nth 6 TrayMEDData) ; FlangeSize
			       )
		           TrayEntity
	)
)
      	  
(princ "Done.")
