//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAD001 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=TTD-6NNYNK3\\ARVADACORE;Database=CoreTools;Integrated Security=SSPI ")]
        public string connstr {
            get {
                return ((string)(this["connstr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=DESKTOP-UGG2A0V\\MDDEVELOPMENT;Database=EngineeringData;Trusted_Connection=" +
            "True;")]
        public string connstrlocal {
            get {
                return ((string)(this["connstrlocal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=mooredesign.database.windows.net,1433;Initial Catalog=CoreTools;Persist Se" +
            "curity Info=False;User ID=clintmoore;Password=\"AzuretnilCM1967!1\";MultipleActive" +
            "ResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30" +
            ";")]
        public string constrazure {
            get {
                return ((string)(this["constrazure"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=TTD-6NNYNK3\\ARVADACORE;Database=CoreTools;Integrated Security=SSPI ")]
        public string connstrarvada {
            get {
                return ((string)(this["connstrarvada"]));
            }
        }
    }
}
