;; MED2026 first-run path setup. Safe to run more than once.
(vl-load-com)
(defun C:MED2026SETUP ( / root support paths trusted )
  (setq root (getenv "MED2026"))
  (if (not root) (setq root "C:\\MED2026"))
  (setq support (strcat root "\\Support"))
  (setq paths (getvar "ACADPREFIX"))
  (if (not (vl-string-search (strcase support) (strcase paths)))
    (setvar "ACADPREFIX" (strcat support ";" paths))
  )
  (setq trusted (getenv "TRUSTEDPATHS"))
  (if (not trusted) (setq trusted ""))
  (if (not (vl-string-search (strcase support) (strcase trusted)))
    (setenv "TRUSTEDPATHS" (if (= trusted "") support (strcat support ";" trusted)))
  )
  (if (findfile "med.cuix")
    (command-s "_.CUILOAD" (findfile "med.cuix"))
  )
  (princ "\nMED2026 paths set. Support is first on the search path.")
  (princ)
)
